spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  application:
    name: TaskManager
  datasource:
    url: jdbc:postgresql://postgres:5432/task_manager_db
    username: admin
    password: 1212
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: taskmanager-client
            client-secret: wOlhKJJIdUzYGGOv6YcauXB36HDaPsqV
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/taskmanager-realm
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/taskmanager-realm
keycloak:
  realm: taskmanager-realm
  url: http://keycloak:8080/
  client-id: taskmanager-client
  client-secret: wOlhKJJIdUzYGGOv6YcauXB36HDaPsqV

  admin-client-id: admin-cli
  admin-username: admin
  admin-password: admin
logging:
  level:
    liquibase: debug