spring:
    application:
        name: TaskManager
    datasource:
        url: jdbc:postgresql://postgres:5432/task_manager_db
        username: admin
        password: 1212
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
    secret: "hj;lskdirfghjo;sidfhgo;iupsdhfgpo;sdiufhugposiudfg"
    expiration-time: 864000000